###################################################
# KitPvP 月色之湖职业战争插件                     #
# 作者：Month_Light、Simon、Ni_xiaoqi、Ruiqi_666  #
###################################################

# 插件版本号
version: B-2.1

# 是否开启调试功能
# 如遇到 Bug 可尝试反馈给作者进行修复
Debug: false

# 语言文件的前缀
Prefix: '&3MoonLake &e>> &f'

# 插件用到的语言文件
# 默认文件为 zh_CN.lang 如有其他
# 例如翻译个 en_US.lang 则只需要
# 将此处修改为 en_US 即可 其他同
Language: zh_CN

# 成功击杀玩家奖励的金币数量
# 如果玩家拥有权限 moonlake.kitpvp.dmoney
# 则获得双倍金币奖励
Money: 3

# 玩家聊天配置
PlayerChat:

  # 聊天的格式化内容
  # 可用变量: %rank, %player, %message
  # 变量解释:
  #   %rank: 玩家的 Rank 等级名称
  #   %player: 玩家的显示名
  #   %message: 玩家发送的消息
  Format: '&f[&b%rank&f] &f%player &e>> &7%message'

# 玩家血条配置
PlayerBar:

  # 玩家的血条标题内容
  # 可用变量: %money, %point, %player
  # 变量解释:
  #   %money: 玩家的金币数量
  #   %point: 玩家的点券数量
  #   %player: 玩家的显示名
  Title: '&cMoonLake 职业战争 &7| &a欢迎您: &b%player &7| &2金币: &b%money &7| &d点券: &b%point'
